### ISSUE TITLE
Enhancement Proposal : Add Dockerfile.dev

### ISSUE THREAD

**Issue by IzioDev** [denpalrius/docker-nestjs-starter#10]
Hi,

I would love to have a Dockerfile for dev, like running Nestjs in a Dockerized environment but having the `project` volume folder mounted to the container so it can handle hot reload.

Or maybe just a docker-compose file that override the `cmd` and mounting the volume ?

What do you think ?

**Comment by denpalrius** [comment]
Hi @izio38. Great suggestion.
Have you tried the [docker-compose.debug.yml](https://github.com/denpalrius/docker-nestjs-starter/blob/master/docker-compose.debug.yml) file?
Would it suffice for your use case?

Also, if you use VS Code, it may be much easier to use the Docker extension and the [Remote-containsers](https://code.visualstudio.com/docs/remote/containers) to launch your code inside a container.

**Comment by IzioDev** [comment]
I think this is perfect, sorry for the late answer.
